### ISSUE TITLE
iOS AppStore Approval - Has this plugin been used successfully in an app that has been approved?

### ISSUE THREAD

**Issue by jeremiahScribblePost** [christocracy/cordova-plugin-background-fetch#33]
I'm doing some due diligence to make sure our app is approved for the app store. Our app will be a communications platform - we'd like to download data periodically in the background.
Has this plugin been used in another app in similar circumstances and been approved by Apple?

**Comment by christocracy** [comment]
Apple will never deny an app using this API.  This API is precisely
designed to allow apps a mechanism to launch periodically in the background
rather than using more aggressive modes such as "location".

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

On Monday, May 23, 2016, Jeremiah Blanch <notifications@github.com> wrote:

> I'm doing some due diligence to make sure our app is approved for the app
> store. Our app will be a communications platform - we'd like to download
> data periodically in the background.
> Has this plugin been used in another app in similar circumstances and been
> approved by Apple?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/33>
>


-- 
Snet form Gmail Mobile

**Comment by jeremiahScribblePost** [comment]
Cool!
That's a very confident answer!
I'll give it a go!

**Comment by pbergner** [comment]
@jeremiahScribblePost was it successful?
